In [1]:
# code for loading the format for the notebook
import os

# path : store the current path to convert back to it later
path = os.getcwd()
os.chdir('../notebook_format')
from formats import load_style
load_style()

In [2]:
os.chdir(path)
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = 8, 6 # change default figure size
plt.rcParams['font.size'] = 12 # and font size

# 1. magic to print version
# 2. magic so that the notebook will reload external python modules
%load_ext watermark
%load_ext autoreload 
%autoreload 2

%watermark -a 'Ethen' -d -t -v -p numpy,pandas,matplotlib

Ethen 2016-09-09 14:15:26

CPython 3.5.2
IPython 4.2.0

numpy 1.11.1
pandas 0.18.1
matplotlib 1.5.1

[movielens dataset](http://grouplens.org/datasets/movielens/)

In [3]:
filepath = os.path.join( 'ml-100k', 'u.data' )
movielens = pd.read_csv( filepath, delimiter = '\t', header = None,
                         names = ['UserID', 'MovieID', 'Rating', 'Datetime'] )
movielens.head()

   UserID  MovieID  Rating   Datetime
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [4]:
movielens['Favorable'] = movielens['Rating'] > 3
movielens.head()

   UserID  MovieID  Rating   Datetime Favorable
0     196      242       3  881250949     False
1     186      302       3  891717742     False
2      22      377       1  878887116     False
3     244       51       2  880606923     False
4     166      346       1  886397596     False

In [5]:
ratings = movielens[ movielens['UserID'].isin(range(200)) ]
favorable_ratings = ratings[ ratings["Favorable"] ]

In [6]:
favorable_reviews_by_users = { k: frozenset(v.values) for k, v in 
                               favorable_ratings.groupby("UserID")["MovieID"] }

In [7]:
movielens[ movielens['UserID'] == 1 ]

       UserID  MovieID  Rating   Datetime Favorable
202         1       61       4  878542420      True
305         1      189       3  888732928     False
333         1       33       4  878542699      True
334         1      160       4  875072547      True
478         1       20       4  887431883      True
639         1      202       5  875072442      True
687         1      171       5  889751711      True
820         1      265       4  878542441      True
933         1      155       2  878542201     False
972         1      117       3  874965739     False
1167        1       47       4  875072125      True
1299        1      222       4  878873388      True
1382        1      253       5  874965970      True
1440        1      113       5  878542738      True
1617        1      227       4  876892946      True
1780        1       17       3  875073198     False
1989        1       90       4  878542300      True
2328        1       64       5  875072404      True
3049        1       92       3  876892425     False
3059        1      228       5  878543541      True
3171        1      266       1  885345728     False
3191        1      121       4  875071823      True
3234        1      114       5  875072173      True
3246        1      132       4  878542889      True
3248        1       74       1  889751736     False
3260        1      134       4  875073067      True
3358        1       98       4  875072404      True
3377        1      186       4  875073128      True
3431        1      221       5  887431921      True
3710        1       84       4  875072923      True
...       ...      ...     ...        ...       ...
74577       1      165       5  874965518      True
74847       1      116       3  878542960     False
75385       1      198       5  878542717      True
77073       1      124       5  875071484      True
77238       1       95       4  875072303      True
77630       1      217       3  876892676     False
78171       1       58       4  878542960      True
78695       1      142       2  878543238     False
78817       1      216       5  876892701      True
81463       1      126       2  875071713     False
81568       1       83       3  875072370     False
82444       1      231       1  876893031     False
82786       1      204       5  875072688      True
83307       1        3       4  878542960      True
84793       1      207       5  875073067      True
85377       1      244       2  887431973     False
85557       1       19       5  875071515      True
86585       1       29       1  878542869     False
87831       1       18       4  887432020      True
87967       1       59       5  876892817      True
88021       1       15       5  875071608      True
88259       1      111       5  889751711      True
88262       1       52       4  875072205      True
88893       1       88       4  878542791      True
89876       1       13       5  875071805      True
92049       1       28       4  875072173      True
92487       1      172       5  874965478      True
94019       1      122       3  875241498     False
96699       1      152       5  878542589      True
99073       1       94       2  875072956     False

[272 rows x 5 columns]

In [8]:
num_favorable_by_movie = ( ratings[["MovieID", "Favorable"]]
                           .groupby("MovieID").sum() )
num_favorable_by_movie.head()

         Favorable
MovieID
1             66.0
2              5.0
3              4.0
4             21.0
5              6.0

In [9]:
frequent_itemsets = {}
min_support = 50

# k=1 candidates are the ones with more than min_support favourable reviews
frequent_itemsets[1] = dict((frozenset((movie_id,)), row["Favorable"])
                                for movie_id, row in num_favorable_by_movie.iterrows()
                                if row["Favorable"] > min_support)

In [10]:
frequent_itemsets[1]

{frozenset({286}): 59.0,
 frozenset({7}): 67.0,
 frozenset({64}): 58.0,
 frozenset({79}): 58.0,
 frozenset({258}): 83.0,
 frozenset({50}): 100.0,
 frozenset({313}): 60.0,
 frozenset({174}): 74.0,
 frozenset({100}): 89.0,
 frozenset({181}): 79.0,
 frozenset({1}): 66.0,
 frozenset({127}): 70.0,
 frozenset({172}): 59.0,
 frozenset({98}): 70.0,
 frozenset({56}): 67.0,
 frozenset({9}): 53.0}

## Reference

https://github.com/asaini/Apriori

https://github.com/timothyasp/apriori-python