In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('static/data/' + 'bankcase' + '.csv')

In [7]:
data

,ID,CUST_OPN_DT,NBROPN,AGE,CITY,STATE,PSTL_CD_5,PSTL_CD_4,NBR_OF_CHLD_IN_HH,OCCUP_OF_1ST_INDV,...,AUTO_LOAN_BAL,INV_FLG,INVST_AMT,ATM_FLG,POS_FLG,CSR_FLG,IVR_FLG,WEB_FLG,TLR_FLG,CRV
0,22794,07/15/1994,3,35.0,SEATTLE,WA,98105.0,2038.0,1.0,O,...,0.00,N,NaN,Y,Y,Y,NaN,Y,Y,-23595.61
1,23835,01/07/1996,2,54.0,BELLINGHAM,WA,98225.0,6304.0,0.0,1,...,0.00,N,NaN,Y,Y,NaN,N,NaN,Y,-6787.06
2,2597,04/01/1974,7,61.0,ROCHESTER,MN,55901.0,2473.0,0.0,Z,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4824.87
3,44853,07/26/1982,1,52.0,SAN ANSELMO,CA,94960.0,1629.0,2.0,1,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4574.78
4,4388,10/01/1977,1,55.0,ELY,MN,55731.0,1622.0,1.0,Z,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3726.99
5,23239,01/01/1981,2,86.0,PORTLAND,OR,97215.0,1041.0,0.0,8,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2961.14
6,29930,02/15/1995,1,56.0,CINCINNATI,OH,45251.0,0.0,NaN,NaN,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2608.21
7,39774,11/01/1999,2,40.0,POPLAR BLUFF,MO,63901.0,8096.0,1.0,O,...,0.00,N,NaN,Y,Y,NaN,NaN,NaN,Y,-39481.94
8,5385,11/20/1997,1,50.0,AURORA,CO,80014.0,4957.0,0.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2557.93
9,6297,04/07/2000,2,32.0,GRANDVIEW,WA,98930.0,1655.0,1.0,P,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2248.68
10,37616,10/03/1998,1,25.0,OAK PARK,IL,60304.0,1504.0,0.0,O,...,0.00,N,NaN,Y,Y,NaN,Y,Y,N,-1691.12
11,46882,01/01/1962,1,87.0,BELLEVUE,WA,98009.0,134.0,0.0,NaN,...,0.00,N,NaN,N,N,NaN,NaN,Y,N,-1444.52
12,15561,09/06/2005,1,22.0,AUSTIN,AR,72007.0,8859.0,0.0,4,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1380.15
13,2340,04/01/1992,1,69.0,LONGMONT,CO,80501.0,1953.0,0.0,F,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1141.97
14,8367,10/04/2002,1,22.0,MADISON,WI,53703.0,1129.0,NaN,P,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,Y,-892.60
15,13511,03/24/1995,2,21.0,OVERLAND PARK,KS,66209.0,4021.0,0.0,N,...,0.00,N,NaN,Y,Y,NaN,NaN,Y,Y,-733.34
16,41809,06/12/1995,1,77.0,KANSAS CITY,MO,64127.0,1202.0,0.0,2,...,0.00,Y,0.00,NaN,Y,NaN,NaN,NaN,Y,-530.54
17,46105,06/03/1985,4,32.0,SAN DIEGO,CA,92107.0,1727.0,0.0,2,...,0.00,Y,6160.14,Y,Y,N,Y,Y,Y,-465.32
18,3507,09/05/1985,1,45.0,SAVAGE,MN,55378.0,1630.0,2.0,C,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-462.43
19,38177,02/24/1995,1,44.0,PURCELL,MO,64857.0,379.0,1.0,1,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-446.80
20,1121,05/01/1969,2,72.0,OMAHA,NE,68144.0,2910.0,1.0,1,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,Y,-403.68
21,7589,03/13/2002,1,56.0,ALBUQUERQUE,NM,87114.0,3497.0,1.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-380.54
22,45859,03/14/1995,4,29.0,SEATTLE,WA,98144.0,3006.0,0.0,O,...,0.00,N,NaN,Y,Y,NaN,N,Y,Y,-365.44
23,4727,08/08/1990,1,60.0,BROOKFIELD,CT,6804.0,215.0,0.0,NaN,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-348.53
24,42370,03/05/2001,7,32.0,DAYTON,OH,45415.0,1803.0,1.0,O,...,0.00,N,NaN,Y,Y,N,Y,Y,Y,-343.41
25,8695,12/13/2002,11,53.0,EVERETT,WA,98208.0,7517.0,0.0,O,...,0.00,N,NaN,NaN,NaN,NaN,N,NaN,Y,-338.24
26,39355,10/04/1990,2,65.0,MILWAUKEE,WI,53213.0,3577.0,0.0,Z,...,0.00,Y,0.00,NaN,Y,N,NaN,NaN,Y,-323.23
27,9421,04/25/2003,2,31.0,NEW ALBANY,IN,47150.0,1832.0,1.0,5,...,0.00,N,NaN,Y,Y,NaN,Y,Y,Y,-319.39
28,32251,07/06/2006,1,38.0,KENNESAW,GA,30152.0,2518.0,1.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,Y,NaN,-297.54
29,31790,04/13/2006,1,44.0,LOS ANGELES,CA,90056.0,1356.0,1.0,N,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-296.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,3669,06/06/1986,5,46.0,SAINT PAUL,MN,55108.0,1731.0,1.0,N,...,0.00,N,NaN,N,NaN,N,NaN,Y,N,6904.06
9971,30126,03/04/2005,2,28.0,ROSEMOUNT,MN,55068.0,1350.0,0.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,Y,NaN,6947.47
9972,35524,08/29/1990,6,43.0,MADISON,WI,53717.0,2710.0,1.0,Z,...,0.00,Y,387737.57,Y,Y,NaN,NaN,Y,Y,7158.03
9973,7217,09/11/2001,3,57.0,MADISON,SD,57042.0,2908.0,0.0,O,...,0.00,N,NaN,N,Y,NaN,NaN,Y,Y,7236.44
9974,37567,10/05/1990,4,40.0,SAINT LOUIS,MO,63122.0,3431.0,1.0,3,...,12580.39,N,NaN,Y,Y,NaN,Y,NaN,Y,7326.03
9975,30688,07/06/2005,1,68.0,BOSTON,MA,2116.0,5914.0,2.0,1,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7346.57
9976,46615,08/30/1993,5,35.0,BOTHELL,WA,98011.0,3439.0,0.0,O,...,18739.05,N,NaN,Y,Y,NaN,Y,NaN,Y,7416.37
9977,34723,10/09/1999,1,92.0,MILWAUKEE,WI,53222.0,3899.0,0.0,8,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,Y,7452.80
9978,47726,07/14/1993,3,57.0,PORTLAND,OR,97219.0,6302.0,1.0,E,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7513.55
9979,39255,07/29/1993,1,65.0,NAPERVILLE,IL,60540.0,6252.0,0.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7525.85
9980,30955,09/21/2005,1,38.0,ANDOVER,MN,55304.0,1913.0,1.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7815.23
9981,44270,09/28/1992,1,73.0,CEDAR RAPIDS,IA,52403.0,7041.0,0.0,2,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7889.93
9982,24335,03/28/1995,3,51.0,HUDSON,OH,44236.0,4333.0,1.0,3,...,0.00,N,NaN,Y,NaN,NaN,NaN,Y,Y,7979.43
9983,32306,06/30/2006,1,38.0,CUMMING,GA,30040.0,3862.0,2.0,3,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8429.71
9984,29525,10/09/2003,1,36.0,MONTROSE,CA,91020.0,1719.0,1.0,1,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8434.30
9985,22297,11/02/1987,2,51.0,HAM LAKE,MN,55304.0,4285.0,1.0,F,...,23423.31,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8518.51
9986,23825,07/12/1996,5,32.0,EAGLE,ID,83616.0,4891.0,0.0,O,...,13145.06,N,NaN,Y,Y,NaN,NaN,Y,Y,8558.63
9987,8021,05/24/2001,5,39.0,BOZEMAN,MT,59715.0,3721.0,0.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8613.14
9988,28860,05/25/2004,3,57.0,ROCKLIN,CA,95765.0,4856.0,0.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8819.70
9989,39335,02/01/1988,5,50.0,MIDDLETON,WI,53562.0,1935.0,0.0,3,...,0.00,Y,64598.02,NaN,NaN,NaN,NaN,NaN,Y,8911.50
9990,32103,05/15/2006,1,NaN,KAPOLEI,HI,96707.0,2452.0,1.0,N,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8969.73
9991,47942,06/08/1990,1,55.0,EUGENE,OR,97405.0,9734.0,0.0,Z,...,0.00,N,NaN,Y,NaN,NaN,Y,Y,Y,9044.03
9992,41854,02/18/1982,7,57.0,TOPEKA,KS,66610.0,1503.0,0.0,2,...,0.00,N,NaN,Y,Y,NaN,NaN,Y,N,10985.53
9993,32008,03/09/2006,1,52.0,FT WASHINGTON,MD,20744.0,1510.0,1.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11192.30
9994,28317,01/31/2004,1,38.0,DRYDEN,MI,48428.0,9227.0,1.0,O,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11969.74
9995,46117,04/27/1990,1,54.0,MERCER ISLAND,WA,98040.0,5458.0,0.0,1,...,0.00,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12645.30
9996,41954,05/03/1988,8,50.0,SAINT LOUIS,MO,63117.0,1005.0,0.0,O,...,0.00,N,NaN,N,NaN,NaN,NaN,Y,Y,13690.65
9997,5773,03/19/1999,4,38.0,HENDERSON,NV,89011.0,3141.0,0.0,NaN,...,0.00,Y,0.00,Y,Y,NaN,NaN,Y,Y,15415.41
9998,46369,12/01/1946,5,96.0,SPOKANE,WA,99203.0,2540.0,0.0,8,...,0.00,Y,541640.62,NaN,NaN,NaN,NaN,NaN,Y,19859.39
9999,3487,02/01/1968,3,72.0,SCOTTSDALE,AZ,85255.0,2367.0,0.0,O,...,0.00,N,NaN,N,NaN,N,N,NaN,Y,21422.80